---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ repo_keys }}"


- name: Add repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ repos }}"

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: install package
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ packages }}"